/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./src/components/icons/ArrowIcon.vue')['default']
    Burger: typeof import('./src/components/menu/Burger.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    DropfiltersItem: typeof import('./src/components/DropfiltersItem.vue')['default']
    ListPage: typeof import('./src/components/ListPage.vue')['default']
    MapPage: typeof import('./src/components/MapPage.vue')['default']
    MapPopup: typeof import('./src/components/map/MapPopup.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectGroup: typeof import('radix-vue')['SelectGroup']
    SelectLabel: typeof import('radix-vue')['SelectLabel']
    Sidebar: typeof import('./src/components/menu/Sidebar.vue')['default']
    StrokeIcon: typeof import('./src/components/icons/StrokeIcon.vue')['default']
  }
}
